feat: добавлена схема БД
PorotikovSergey/java-filmorate pull request #3
Opened 2022-07-02 09:48 UTC by PorotikovSergey

2022-07-02 13:41 UTC, PorotikovSergey commented
![БД](QuickDBD-Filmorate (2).png)

2022-07-02 22:58 UTC, PorotikovSergey commented
![Новая схема БД](https://github.com/PorotikovSergey/java-filmorate/blob/add-database/QuickDBD-Filmorate%20(5).png)

2022-07-03 06:34 UTC, PorotikovSergey commented
![Вот теперь точно последняя схема БД](https://github.com/PorotikovSergey/java-filmorate/blob/add-database/QuickDBD-Filmorate%20(6).png)

2022-07-11 21:18 UTC, PorotikovSergey commented
![Схема БДу](https://github.com/PorotikovSergey/java-filmorate/blob/add-database/QuickDBD-Filmorate%20(8).png)

2022-07-12 18:58 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/FilmorateApplication.java
> +
еще одна пустая строка не нужна

2022-07-12 19:01 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +public class FilmDbStorage implements FilmStorage {
лучше общее название для всех реализаций интерфейса оставить одинковым - FilmStorage
а особенность реализации добавлять в начале или конце DbFilmStorage или FilmStorageDbImpl

2022-07-12 19:04 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +    public Mpa getMPA(int filmId) {
сокращения тоже нужно писать в camelCase
`getMpa()`

2022-07-12 19:06 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private LinkedHashSet<Genre> genres = new LinkedHashSet<>();
тип поля должен быть Set, а реализация уже любая

2022-07-12 19:07 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/model/Genre.java
> +    public Genre(int id, String name) {
можно добавить ломбок аннотации
NoArgConstructor
AllArgConstructor

2022-07-12 19:10 UTC, makholin commented on src/test/java/ru/yandex/practicum/filmorate/dao/FilmDbStorageTest.java
> +    @Transactional
транзакций не должно быть в тестовых методах
они должны быть указаны на методах стораджа, или вообще коммиты должны делаться вручную у jdbc template
об этом подробнее можно в инете прочитать или у куратора спросить

ПС советую разобраться, как работает эта аннотация в спринге, потому что по ней часто спрашивают на собеседованиях

2022-07-12 19:11 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +public class FilmDbStorage implements FilmStorage {
но этот вариант тоже норм смотрится, так что его тоже можно оставить

2022-07-12 19:12 UTC, makholin requested changes
Нужно исправить замечания

2022-07-15 07:17 UTC, makholin approved these changes
Работа принята

2022-07-18 16:38 UTC, merged